version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: neoxame
    networks:
      mynetwork:
        ipv4_address: 172.17.0.2
    ports:
      - "3306:3306"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://172.17.0.2:3306/neoxame
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - mynetwork
    ports:
      - "8083:8083"

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.0.0/16
