version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - backend-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=mysql
      - DB_NAME=neoxame
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - backend-network

networks:
  backend-network:

volumes:
  mysql-data:
